### ISSUE TITLE
1.18 Support: Mobs Spawn at blocklight 0 only

### ISSUE THREAD

**Issue by jordankothe9** [Masstrix/Eternal-Light#14]
Support the new change in 1.18 by showing red particals at blocks with a light level of 0.

The current behavior is showing red particals in light levels of 1-7 but mobs are not able to spawn.

Note that mobs still spawn in a skylight of 0-7 assuming blocklight is still 0.

**Comment by jordankothe9** [comment]
I've created a fork of this project with the proposed changes made, as well as a pull request. Until the pull request is accepted check out my fork here: https://github.com/jordankothe9/Eternal-Light/releases/tag/1.8

**Comment by TonyGravagno** [comment]
I see your change. It's good. For anyone who finds this project, it's safe to download and use the tagged .jar file.

I built from source, created my own JAR, and am running this in v1.18. It makes sense now to run with a render distance of 20. Set in config.yml, scanner>radius. or use command "/eternallight renderDistance 20". This is the max that the game allows us to use. Personally I'm going to increase that to 50. Maybe that's the next enhancement for this fine plugin.

Thanks for forking. Good idea.

**Comment by TonyGravagno** [comment]
@Masstrix I request and recommend that you merge this PR and publish this as v1.8. Thanks.

**Comment by TonyGravagno** [comment]
Nice implementation in https://github.com/Masstrix/Eternal-Light/commit/57c65983931866db9afea6b93f3b6bd0cca0b85e - Thanks.
