### ISSUE TITLE
java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided

### ISSUE THREAD

**Issue by Lucas-R-Ross** [Masstrix/Eternal-Light#16]
Getting the attached console error when toggling /ll. Any help appreciated.
[error.txt](https://github.com/Masstrix/Eternal-Light/files/8310237/error.txt)

**Comment by Masstrix** [comment]
Looks like this is an older version of the plugin. I'd recommend updating it if you can to the latest. I'll be putting out a new release soon with some new features.
