### ISSUE TITLE
Users cannot access /ll or /ll mode

### ISSUE THREAD

**Issue by tserversbfs** [Masstrix/Eternal-Light#4]
Thank you for making this mod. This is going to be a huge help.

**Comment by Masstrix** [comment]
Do they have the permission eternallight.use?

**Comment by Michael-Koers** [comment]
Hi, can you provide an example/update the docs to show how to configure it? I was expecting it to configure it either like this:
`
eternallight:
    use: true
    mode: true
`

or 

`eternallight:
    use: 
    - <Player_Name>
    mode: 
    - <Player_Name>`

But both don't seem to work when I use /el reload, or do I need to fully restart the server? 

Thanks in advance!
