### ISSUE TITLE
Permissions Documentation

### ISSUE THREAD

**Issue by creightonjoiner** [Masstrix/Eternal-Light#5]
As a server admin, I would like to give my players the ability to use this plugin. However, there doesn't seem to be any documentation on how to set these permissions. Putting eternallight.admin/use/mode in config.yml ends up with a bunch of errors flooding the console and then when I return to the file it has been reset to default. More explanation would be fantastic.

**Comment by ZweetPanda** [comment]
@Masstrix Can you extend the documentation on how to use the permissions?

**Comment by Masstrix** [comment]
> @Masstrix Can you extend the documentation on how to use the permissions?

Yep I can do that, I'm a bit busy at the moment with study and work but I'll update the documentation when I find some spare time so it's clear and concise for everyone to use. I might if the permissions don't make enough sense redo them to make more sense.

**Comment by ZweetPanda** [comment]
> > @Masstrix Can you extend the documentation on how to use the permissions?
> 
> Yep I can do that, I'm a bit busy at the moment with study and work but I'll update the documentation when I find some spare time so it's clear and concise for everyone to use. I might if the permissions don't make enough sense redo them to make more sense.

Thanks, that sounds good!

**Comment by Masstrix** [comment]
> > > @Masstrix Can you extend the documentation on how to use the permissions?
> > 
> > 
> > Yep I can do that, I'm a bit busy at the moment with study and work but I'll update the documentation when I find some spare time so it's clear and concise for everyone to use. I might if the permissions don't make enough sense redo them to make more sense.
> 
> Thanks, that sounds good!

If you have any other issues or suggestions/improvements ideas just make a new issue with the suggestion tag.

**Comment by Yarkhan** [comment]
I'm new to Spigot and custom servers, this took me a while to figure out. 

To set the permissions, open the file `permissions.yml` (create it if doesn't exist) in the spigot directory (the one that contains spigot.yml and bukkit.yml) and paste the following:

```
eternallight.admin: 
  default: true
eternallight.use:
  default: true
eternallight.mode: 
  default: true
```

You can see the available options in the documentation to the permissions.yml file: https://bukkit.gamepedia.com/Permissions.yml

@Masstrix, I can send a pull request updating the Readme if you want (and the info above is correct).

Also, thank you so much for the time you've put in this plugin, its really useful.

**Comment by Masstrix** [comment]
> I'm new to Spigot and custom servers, this took me a while to figure out.
> 
> To set the permissions, open the file `permissions.yml` (create it if doesn't exist) in the spigot directory (the one that contains spigot.yml and bukkit.yml) and paste the following:
> 
> ```
> eternallight.admin: 
>   default: true
> eternallight.use:
>   default: true
> eternallight.mode: 
>   default: true
> ```
> 
> You can see the available options in the documentation to the permissions.yml file: https://bukkit.gamepedia.com/Permissions.yml
> 
> @Masstrix, I can send a pull request updating the Readme if you want (and the info above is correct).
> 
> Also, thank you so much for the time you've put in this plugin, its really useful.

Yeah for sure, if you make a pull request with those changes I can accept it. I haven't actually used permission plugins or the permissions.yml for years myself so just have to kind of assume people understand it a bit. That'd be great if you could put those changes through though.

**Comment by Yarkhan** [comment]
There you go :).
https://github.com/Masstrix/Eternal-Light/pull/13

Any other minecraft plugin / project you are actively working right now? I've been wanting to dip my toes in these things for quite a while now (specially if you are using kotlin). I might have some spare time in the future.

Once again, thanks. This plugin helped us a lot on my home server :)
